### ISSUE TITLE
Workflow failed

### ISSUE THREAD

**Issue by angpiz** [MonashBioinformaticsPlatform/laxy#261]
Hello Laxy!

My analysis workflow failed with the following error running nf-core/rnaseq: Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 255.

The full error message was:

Error executing process > 'NFCORE_RNASEQ:RNASEQ:PREPARE_GENOME:RSEM_PREPAREREFERENCE_TRANSCRIPTS (rsem/genome.fa)'

Caused by:
  Process `NFCORE_RNASEQ:RNASEQ:PREPARE_GENOME:RSEM_PREPAREREFERENCE_TRANSCRIPTS (rsem/genome.fa)` terminated with an error exit status (255)

Command executed:

  rsem-prepare-reference \
      --gtf genome_genes.gtf \
      --num-threads 48 \
       \
      rsem/genome.fa \
      rsem/genome
  
  rsem-calculate-expression --version | sed -e "s/Current version: RSEM v//g" > rsem.version.txt

Command exit status:
  255

Command output:
  rsem-extract-reference-transcripts rsem/genome 0 genome_genes.gtf None 0 rsem/genome.fa
  Parsed 200000 lines
  Parsed 400000 lines
  Parsed 600000 lines
  Parsing gtf File is done!
  "rsem-extract-reference-transcripts rsem/genome 0 genome_genes.gtf None 0 rsem/genome.fa" failed! Plase check if you provide correct parameters/options for the pipeline!

Command error:
  WARNING: Skipping mount /usr/local/singularity/3.7.1/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Transcript rna27035 is out of chromosome chr5's boundary!

Work dir:
  /fs03/pl41/laxy/jobs/2wvHqvq7xqQNar9ks5uQgW/output/work/29/7efb25e544d0e496ff45349f54a730

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.

I am no programmer, is there something wrong with the files I have used? They worked on the RNAsik pipeline.

Thank you!
Angela

**Comment by pansapiens** [comment]
Hi Angela - after a bit of investigation, it appears this was caused by a temporary network failure from the compute backend to AWS where the reference genome is downloaded, causing the downloaded reference genome to be truncated. The desired behavior would be for nf-core/rnaseq (3.2) to fail immediately when the reference download fails, it instead forges ahead and only fails later when the GTF is inconsistent with the truncated FASTA. I was able to replicate this by running `rsem-extract-reference-transcripts` manually.

The easy solution from your end is to try again, since the external network on the production backend seems to be behaving again.

With regard to a longer term fix - not a case which is straightforward to fix within Laxy (other than more informative error messages or transparent retires), but something that might be fixable upstream in nf-core/rnaseq (eg more reliable download retries, fail fast on download fail). It may have already been improved in a newer nf-core/rnaseq release also (Laxy will at some point track newer nf-core/rnaseq releases).
