### ISSUE TITLE
Laxy analysis has been running for 5 days on one sample

### ISSUE THREAD

**Issue by angpiz** [MonashBioinformaticsPlatform/laxy#279]
Hello!

I've had an unusual sample where the sequencing was divided into several files, so I have 4 R1 files and 4 R2 files associated to the same sample. To upload it via Mediaflux links, I have created a csv file containing 4 lines, where the sample name is the same and each R1 is matched to the same R2 file. 

The laxy analysis has been now running for 5 days: is it correct? Is it something I need to change?

Thank you!

Angela

**Comment by pansapiens** [comment]
Looking at this run on production, it seems the reference download from Ensembl stalled indefinitely. Downloads from Ensembl genomes have become very slow in recent times; this is a known issue which we hope to fix at some point. I think the reference genome you want (GRCh38.release-109) is now an option in the pre-downloaded references dropdown, so best to re-run and use that, since it's exactly the same as http://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz .
