### ISSUE TITLE
Pipeline erroring out with segmentation error (139)

### ISSUE THREAD

**Issue by amdouek** [MonashBioinformaticsPlatform/laxy#287]
Hi,

I have been trying to execute a Laxy job via `nf-core/rnaseq` (6 samples, PE150, about 44mil clean reads per sample, example job ID 77VQoSSjG8F3Fh6GeusyL2) which has persistently been failing in ~3 hours at the `NFCORE_RNASEQ:RNASEQ:FASTQ_SUBSAMPLE_FQ_SALMON:SALMON_QUANT` step with error exit status 139. The pipeline seems to handle some of the samples fine and only encounters this error about midway through the job; other (larger) jobs using samples from the same sequencing run have proceeded without issue.

[execution_report_2024-03-17_05-23-03.pdf](https://github.com/MonashBioinformaticsPlatform/laxy/files/14631271/execution_report_2024-03-17_05-23-03.pdf)

I initially thought this might be due to errors in the fastq files introduced during upload to NextCloud (error 504 when assembling chunks) but this behaviour was also observed with other fastq files in jobs that completed successfully. I suppose there is a possibility that one or more of the .fastq files are corrupt but I don't know how to check this. Any ideas as to the cause of the above error 139 and what could be done to resolve it?

Thanks!

- Alon

**Comment by pansapiens** [comment]
Hi Alon - it looks like this is a bug in the version of Salmon (1v1.9.0) associated with nf-core/rnaseq v3.10.1, and was fixed by running the job using v3.12.0 (which uses a newer version of Salmon, v1.10.1). Not really a Laxy bug per-se. I'll close this since it's not something we can easily fix, other that ensure we use more up-to-date versions of nf-core/rnaseq and Salmon and hope this issue has been fixed upstream.
