### ISSUE TITLE
Possibly related to issue 10, merge two completed jobs together if the same parameters were used in the pipeline

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#33]
New use case, and related to previous thoughts I suppose. 

To do with merging data. If separate pipeline runs of different samples were done with the same parameters (pipeline version, reference genome), could they be merged?

so you get:

aggregated multiqc 
aggregated counts
aggregated location of all derivative files, short of rerunning everything.

Speaks to almost instantaneous results and outcome rather than waiting for processing again.

**Comment by pansapiens** [comment]
This would take considerable developer effort to implement correctly, and given that an alternative already exists (just re-run everything with all samples in the same run), it's not something I can see being provided any time soon.

One alternative would be to build this functionality into RNAsik, where if alignments and counts from the previous jobs could be used as input to a new job RNAsik would handle re-using and merging that data efficiently (you could file a feature request on RNAsik :) ).

It does make some sense to allow output files of a job to be directly used as input files for a new one, however I'm cautious about features like this since it verges dangerously into 'workflow builder / manager' territory, which isn't within the goals or roadmap of Laxy.
